### ISSUE TITLE
favours students high in list

### ISSUE THREAD

**Issue by bkirman** [DrRowland/SPA#1]
If I read it right, getSomeUnassignedStudentWithNonEmptyList reads students from the list in order. In this way students at the top of the list get their first favoured project. Therefore later students may be unfairly left in the unallocated pool. A simple but inelegant solution is to shuffle the list of students after it is read from the file

**Comment by shearer12345** [comment]
I agree that this favours students towards the top of that list.

@bkirman your proposed solution is fine with me.

Alternatively, we could consider that student who apply earlier will be those higher in the list, and therefore could be allowed that (small) bias?

@DrRowland - your thoughts?

**Comment by DrRowland** [comment]
Hmm.. well they will get reassigned if the solution does not converge with that initial allocation, however, I can add python's random.choice (pick a random element from a list) or just shuffle like you suggest.

**Comment by DrRowland** [comment]
Actually probably I will just shuffle all lists (lecturers too) for similar reasons. Thanks for the feedback. -D

**Comment by shearer12345** [comment]
sounds good ;-)

**Comment by DrRowland** [comment]
Actually they're sets, not lists... e.g.
    >>> {1,2,3} == {3,2,1}
    True
    >>> [1,2,3] == [3,2,1]
   False
So instead I can use random.sample...
    >>> print sample(myset,1)

**Comment by bkirman** [comment]
:ok_hand: :beers: :ok_hand:
